### PR TITLE
Updated README.md to resolve #56

### LINKED ISSUE #56: README improvements
- [x] Prerequisite should say people should clone the project :)
- [x] Add a Contact Us paragraph with the link to code for life contact form

### PR DESCRIPTION
**Pull request by OlafSzmidt**

### CODE REVIEW

**Comment by CelineBoudier** [comment]
@danalex97 I would have liked to review the changes before :P

**Comment by danalex97** [comment]
@CelineBoudier Will just review(not merge) from now on. :laughing:

**Comment by CelineBoudier** [comment]
bwahahah you just want the points for your own github profile stats :D ;)

**Comment by danalex97** [comment]
Guilty :laughing:

**Pull request merged**
