### PR TITLE
WebGL Building: Namespace Issue

### PR DESCRIPTION
**Pull request by OlafSzmidt**
Quickfix that should resove #26. The build times will still be extremely long but they will be solved in a different issue.

### CODE REVIEW

**Comment by CelineBoudier** [comment]
If you write "fixes #26" in the commit message, the issue will be closed automatically when this is merge btw :)

**Comment by OlafSzmidt** [comment]
Always forget :P

**Comment by OlafSzmidt** [comment]
Yep. Will be done with #62.

**Comment by OlafSzmidt** [comment]
@CelineBoudier - any remarks before we merge?

**Pull request merged**
