### PR TITLE
Future skin

### PR DESCRIPTION
**Pull request by mariaFernando**
screen shot 2018-01-23 at 11 07 08
screen shot 2018-01-23 at 11 07 25
screen shot 2018-01-23 at 11 07 30
screen shot 2018-01-23 at 11 07 40
screen shot 2018-01-23 at 11 07 46

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Did you run the tests? Are there any docs to update in the wiki?

**Comment by CelineBoudier** [comment]
looks good!

**Comment by mariaFernando** [comment]
screen shot 2018-01-23 at 13 46 16

**Comment by mariaFernando** [comment]
@OlafSzmidt tested 🆗

**Pull request merged**
