### PR TITLE
[New UI] SocketIOWrapper suitable for new message sending

### PR DESCRIPTION
**Pull request by OlafSzmidt**
This is complementary to our other PR in the `aimmo` repository. Link: https://github.com/ocadotechnology/aimmo/pull/616.

**This probably breaks the current UI**.  ~We need to figure out how to have two running side by side. Perhaps some try catch.~ We agreed we only want to serve unity via django.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Agreed we only serve unity via django. Almost ready to merge once tests are written in the main PR.

**Comment by OlafSzmidt** [comment]
Ready to review

**Comment by CelineBoudier** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrniket and @riaJha97)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211)*

**Comment by mrniket** [comment]
If we merge this and make a new release, staging and production would break next time they are deployed right? Since the new ui stuff isn't in master yet

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrniket and @riaJha97)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211#-:-LFHJWPv30v8d7Og0Avg:b-45nnfc)*

**Comment by mrniket** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @OlafSzmidt and @riaJha97)

---

*[UnityProject/Assets/Scripts/UnitySocketIO/SocketIOWrapper.jslib, line 28 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211#-LFHJnKJCy4irJcVMPvv:-LFHJnKJCy4irJcVMPvw:bbss5v1) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/684862d206f1bfe47b405930ac140f7eb3335259/UnityProject/Assets/Scripts/UnitySocketIO/SocketIOWrapper.jslib#L28)):*
> ```
>                     eventData: typeof data === 'undefined' ? '' : JSON.stringify(data)
>                 };
>                 gameInstance.SendMessage(objectName, 'InvokeEventCallback', JSON.stringify(socketData));
> ```

this is fine temporarily but I think just using SendMessage but itself is deprecated

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211)*

**Comment by OlafSzmidt** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @OlafSzmidt and @riaJha97)

---

*[UnityProject/Assets/Scripts/UnitySocketIO/SocketIOWrapper.jslib, line 28 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211#-LFHJnKJCy4irJcVMPvv:-LFHXAdt7nOSFS2aKavq:bb3v8nr) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/684862d206f1bfe47b405930ac140f7eb3335259/UnityProject/Assets/Scripts/UnitySocketIO/SocketIOWrapper.jslib#L28)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

this is fine temporarily but I think just using SendMessage but itself is deprecated
</blockquote></details>

Until the next update of our `react-webgl-unity` package, we can't do much

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/211)*

**Pull request merged**
