### PR TITLE
Changed camera parameters and blocked the zoom

### PR DESCRIPTION
**Pull request by mariaFernando**
Capped the orthographic size and cut the zoom sensitivity in half

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/194)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 6 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7TrOmtreEzD6HYtoqq:-L7TrOmtreEzD6HYtoqr:b-uia2y4) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L6)):*
> ```Smalltalk
> public class MoveCamera : MonoBehaviour
> {
>     public float zoomSpeed = 0.5f;
> ```

Does this need to be public?

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 53 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7TrTWoN3UhA8ogrnvd:-L7TrTWoN3UhA8ogrnve:b-wtqrj0) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L53)):*
> ```Smalltalk
>         {
>             Camera.main.orthographicSize -= zoomSpeed;
>             if (Camera.main.orthographicSize <= 1.2f)
> ```

Can we get this `1.2f` and `5.0f` into constants with a name? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by CelineBoudier** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 53 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7TrTWoN3UhA8ogrnvd:-L7U8eNXHkv3GITEyGFk:b-8fx2u7) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L53)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Can we get this `1.2f` and `5.0f` into constants with a name? 
</blockquote></details>

:+1: 

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 59 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7U8n0WhBL_e5V3uPKS:-L7U8n0X8JdLqOMFEOn9:b-gt2fnu) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L59)):*
> ```Smalltalk
>         {
>             Camera.main.orthographicSize += zoomSpeed;
>             if (Camera.main.orthographicSize >= 5.0f)
> ```

isn't there a min() function in C#? If not, you don't need the equal in >= here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by OlafSzmidt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 59 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7U8n0WhBL_e5V3uPKS:-L7UAXiu43EW6fLjIJkO:bcv0lzt) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L59)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

isn't there a min() function in C#? If not, you don't need the equal in >= here
</blockquote></details>

I'm not convinced we need that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by mrniket** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 6 at r1](https://beta.reviewable.io/reviews/ocadotechnology/aimmo-unity/194#-L7TrOmtreEzD6HYtoqq:-L7UBwRe9u1Y8gMWuSGz:b99e7wr) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L6)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Does this need to be public?
</blockquote></details>

it allows it to be changed via the editor so I would say yes

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 59 at r1](https://beta.reviewable.io/reviews/ocadotechnology/aimmo-unity/194#-L7U8n0WhBL_e5V3uPKS:-L7UCOdY4WHZ8MqCVPfv:b-r1rfni) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L59)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

I'm not convinced we need that
</blockquote></details>

I agree that a min function would make this easier to read. Here is the doc for it: https://msdn.microsoft.com/en-us/library/system.math.min(v=vs.110).aspx

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by OlafSzmidt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by CelineBoudier** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 53 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7TrTWoN3UhA8ogrnvd:-L7ULjrebLxGm4gbMopd:b-ur78ks) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L53)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

same should be a min() function IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by mariaFernando** [comment]
*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 6 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-L7TrOmtreEzD6HYtoqq:-L7UyRZrwOYD5LvyrWJ8:b-czawrx) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/a61a4a1a519acb4f4b59004ef02285e5ebe3fe56/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L6)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

it allows it to be changed via the editor so I would say yes
</blockquote></details>

Made it private because if we need to change it we can change it easily in the code imo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by OlafSzmidt** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by CelineBoudier** [comment]
@mariaFernando For later: if you write "Fixes #issuenumber" in the commit message, it will be linked automatically to the issue ^^

---

Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194#-:-L7V6f6Xml3kW3mbbDLy:b-6dcjlt)*

**Comment by CelineBoudier** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Comment by mrniket** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/194)*

**Pull request merged**
