### PR TITLE
Added damage pickup + material + texture

### PR DESCRIPTION
**Pull request by mariaFernando**
screen shot 2017-12-01 at 10 55 04

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Is the pivot correct? The sword isn't centered but you could have just moved it

**Comment by mariaFernando** [comment]
Yep, the pivot is just beneath the model

**Comment by OlafSzmidt** [comment]
Don't think we want to merge many things at once (movment scripts in a PR dedicated for the damage pikckup) in one pull request, just in case we need to revert back to a specific point later. Also it's quite hard to keep reviewing things like that.

**Comment by OlafSzmidt** [comment]
Fixed git history

**Pull request merged**
