### PR TITLE
Add compass to the game, resolves #198

### LINKED ISSUE #198: Integrate compass on game

### PR DESCRIPTION
**Pull request by OlafSzmidt**
- Adds a new canvas to the **Main** scene.
- As part of the canvas we now have a **Compass** object.
- **Compass** object has a image element.
- **Tests**.
- GIF changed with the new compass in the `README.md`.

The compass should be placed correctly for all resolutions, both full screen or not. [More on this here. ](https://docs.unity3d.com/Manual/UIBasicLayout.html).

### Editor view:
screen shot 2018-03-20 at 12 21 25

### Build view:
screen shot 2018-03-20 at 12 16 05

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo-unity/200)

### CODE REVIEW

**Comment by j4mesholland** [comment]
The compass isn't aligned to the game map. I will take a look.

**Comment by CelineBoudier** [comment]
I agree, the alignment doesn't work

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-:-L83KeIo8xgXwWX8-iTD:beotrzz)*

**Comment by mrniket** [comment]
I think the misalignment is due to the fact that the unity camera is not correct, rather than the image. I would probably say it's in the scope of this PR to make sure they align

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L872MoBBHUK7pNsxmmi:-L872MoBBHUK7pNsxmmj:bnrm6ee) (no related file):*
> View on GitHub
If it doesn't take too long, can we look at adding this to the Levels as well?

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871NnM8kw8ylmsxZ7J:-L871NnM8kw8ylmsxZ7K:bbfazwv) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/README.md#L5)):*
> https://media.giphy.com/media/25JgIPFeELINMlkKeV/giphy.gif

Just a reminder to update this gif when the alignment is fixed

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 22 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871cab4td4T8PeaLt2:-L871cab4td4T8PeaLt3:by95vcz) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L22)):*
> ```Smalltalk
>         public void TestMainSceneHasCompass()
>         {
>             SetUpMainScene();
> ```

you can put this in a setup method

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 77 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871kWv5GWvSVEPxVra:-L871kWv5GWvSVEPxVrb:b-fnzcn3) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L77)):*
> ```Smalltalk
>         }
>     }
> }     
> ```

new line :trollface: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-:-L87-5ekWoulLum_cwPv:bc54rdq)*

**Comment by OlafSzmidt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L872MoBBHUK7pNsxmmi:-L87Lo42arKmSDhkfqcE:b6frtwx) (no related file):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

> View on GitHub
If it doesn't take too long, can we look at adding this to the Levels as well?
</blockquote></details>

As discussed with James, leave it for later - opened issue #204 

---

*[README.md, line 5 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871NnM8kw8ylmsxZ7J:-L87NBM1WLZkmjWNi10S:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/README.md#L5)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

> https://media.giphy.com/media/25JgIPFeELINMlkKeV/giphy.gif

Just a reminder to update this gif when the alignment is fixed
</blockquote></details>

Done.

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 22 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871cab4td4T8PeaLt2:-L87NLz-4pQKoYdpgaR1:b5mic67) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L22)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

you can put this in a setup method
</blockquote></details>

Added a NUnit `[SetUp]` attribute.

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 77 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871kWv5GWvSVEPxVra:-L87NbhhXmxSO8Pf7Or-:b-el33dp) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L77)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

new line :trollface: 
</blockquote></details>

Done. :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200)*

**Comment by mrniket** [comment]
Reviewed 3 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 22 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871cab4td4T8PeaLt2:-L8814jLDnRGbZH_SINm:bdhu45g) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L22)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Added a NUnit `[SetUp]` attribute.
</blockquote></details>

We can remove the SetupMainScene call now from each test :)

---

*[UnityProject/Assets/Resources/Images/compass2.png, line 0 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L880y0S7C8k7m3wDHsG:-L880y0S7C8k7m3wDHsH:b5psqgq) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/449d4e3b58d4233655e075268d8801ca21c6b518/UnityProject/Assets/Resources/Images/compass2.png#L0)):*
can we rename this to compass.png?

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 8 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L881EBfCwbHpGMR2N1f:-L881EBfCwbHpGMR2N1g:b6zkzpw) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/449d4e3b58d4233655e075268d8801ca21c6b518/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L8)):*
> ```Smalltalk
>     public float zoomSpeed = 0.5f;
>     private float minCameraCap = 1.2f;
>     private float maxCameraCap = 7.0f;
> ```

What was the reasoning behind this change again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200)*

**Comment by j4mesholland** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 8 at r2](https://beta.reviewable.io/reviews/ocadotechnology/aimmo-unity/200#-L881EBfCwbHpGMR2N1f:-L882AuM7wrV9PaLhqIK:b7o3b39) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/449d4e3b58d4233655e075268d8801ca21c6b518/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L8)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

What was the reasoning behind this change again?
</blockquote></details>

I think it was to fix the camera angles, so the compass directions aligned to the map grid

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo-unity/200)*

**Comment by OlafSzmidt** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[UnityProject/Assets/Editor/Tests/CanvasTests.cs, line 22 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L871cab4td4T8PeaLt2:-L88Me-RpXhTXCIdHrzl:bh06oj9) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/abc95fd82278b3ade6aae0cc93eb75a31dec5b7c/UnityProject/Assets/Editor/Tests/CanvasTests.cs#L22)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

We can remove the SetupMainScene call now from each test :)
</blockquote></details>

Done. Tests passing.

---

*[UnityProject/Assets/Scripts/Camera/MoveCamera.cs, line 8 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L881EBfCwbHpGMR2N1f:-L88MZeaudEY1mtkJ5V6:busifyh) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/449d4e3b58d4233655e075268d8801ca21c6b518/UnityProject/Assets/Scripts/Camera/MoveCamera.cs#L8)):*
<details><summary><i>Previously, j4mesholland (James Holland) wrote…</i></summary><blockquote>

I think it was to fix the camera angles, so the compass directions aligned to the map grid
</blockquote></details>

Because at the new rotation, we need to zoom out more to see the map.

---

*[UnityProject/Assets/Resources/Images/compass2.png, line  at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-L880y0S7C8k7m3wDHsG:-L88MeW7fZwGp0yLPg_P:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo-unity/blob/449d4e3b58d4233655e075268d8801ca21c6b518/UnityProject/Assets/Resources/Images/compass2.png#L)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

can we rename this to compass.png?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200)*

**Comment by mrniket** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200#-:-L899WqzbKl0MIKRFzI4:bnfp4nl)*

**Comment by mrniket** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo-unity/200)*

**Pull request merged**
